version: '3.8'

services:
    nextjs:
        image: nextjs-app:latest
        container_name: nextjs-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis
        restart: unless-stopped

    redis:
        image: redis:7.2-alpine
        container_name: redis-cache
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        restart: unless-stopped

volumes:
    redis-data:
        driver: local
