const SECOND = 1000;

export const Config = {
    SLIDES_REFETCH_INTERVAL: 60 * SECOND,
    ROOM_SCHEDULES_REFETCH_INTERVAL: 60 * SECOND,
    CALENDAR_EVENTS_REFETCH_INTERVAL: 60 * SECOND,
    SLIDE_DURATION: 10 * SECOND,
};
